### ISSUE TITLE
Add HTML minification. Update to use with new version of asset-minifier.

### ISSUE THREAD

**Issue by Atsman** [yogthos/lein-asset-minifier#14]
Hi,

We have to update this plugin to support new feature from related project [asset-minifier](https://github.com/yogthos/asset-minifier).

The issuer in asset-minifier [add html minification](https://github.com/yogthos/asset-minifier/issues/3)

At this moment i see, that the way how configuration for compilers passed through this plugin is not flexible. 

Aleh

**Comment by Atsman** [comment]
@yogthos, is it possible to have a 5 minutes call via skype? I want you to quickly describe plugin's code for me, to understand details. I did some changes and it actually works, but i do not feel comfortable.

**Comment by yogthos** [comment]
Yeah sure thing. I might have a few minutes here in a bit, I'll ping you on Skype once I get a moment.

**Comment by Atsman** [comment]
I am going to do some testing and then will push new major release.

**Comment by yogthos** [comment]
Perfect
