### ISSUE TITLE
Version 0.2.5 does not create minified packages

### ISSUE THREAD

**Issue by tuhlmann** [yogthos/lein-asset-minifier#6]
I just updated my config to use `lein-asset-minifier "0.2.5`.
Now, after `lein clean`, `lein minify-assets` doesn't create anything. Switching back to 0.2.3 or 0.2.4 works as expected.

My configuration is pretty simple:

```
  :minify-assets {
                  :assets { "resources/public/js/landing.min.js"
                            ["resources/vendor-js/jquery/jquery-2.1.4.min.js"
                             "resources/vendor-js/tether/tether.js"
                             "resources/vendor-js/bootstrap/bootstrap.js"
                             "resources/vendor-js/bootstrap/jqBootstrapValidation.js"
                             "resources/vendor-js/freelancer/freelancer.js"
                             "resources/vendor-js/freelancer/cbpAnimatedHeader.js"
                             "resources/vendor-js/freelancer/classie.js"
                             "resources/vendor-js/freelancer/contact_me.js"]

                            "resources/public/js/vendor.min.js"
                            ["resources/vendor-js/jquery/jquery-2.1.4.min.js"
                             "resources/vendor-js/tether/tether.js"
                             "resources/vendor-js/bootstrap/bootstrap.js"
                             "resources/vendor-js/bootstrap/jqBootstrapValidation.js"
                             "resources/vendor-js/custom/page-setup.js"]}}
```

Is there anything I should change when using the new version?

**Comment by yogthos** [comment]
There shouldn't have been, the only change was this pr https://github.com/yogthos/lein-asset-minifier/pull/5 to make relative asset paths resolve relative to lein root.

**Comment by yogthos** [comment]
I can confirm that this does break it, @publicmayhem looks like the change doesn't quite work as expected.

**Comment by publicmayhem** [comment]
Sorry @tuhlmann, I messed up the asset paths when I tried tiding up some code. I've created a pull request which fixes the problem. I hope this will resolve this issue soon.

**Comment by yogthos** [comment]
@tuhlmann should be fixed by this, and `0.2.6` is up on Clojars, let me know if the fix worked https://github.com/yogthos/lein-asset-minifier/pull/7

**Comment by tuhlmann** [comment]
@yogthos @publicmayhem Thanks for the super quick response!

I will check tomorrow and let you know!

**Comment by tuhlmann** [comment]
This works now. Thanks for the speedy fix!
